resources:
- "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
  name: local_route
  virtual_hosts:
  - name: local_service
    domains: ["*"]
    routes:
    # Method-specific route for GET /api/hello
    - match:
        safe_regex:
          regex: "/api/pet/[0-9]+"
        headers:
        - name: ":method"
          exact_match: "GET"
      route:
        cluster: petstore_app_service
    
    # Method-specific route for POST /api/hello
    - match:
        path: "/api/hello"
        headers:
        - name: ":method"
          exact_match: "POST"
      route:
        prefix_rewrite: "/hello"
        cluster: petstore_app_service
    
    # Default route for other methods - returns 405 Method Not Allowed
    - match:
        path: "/api/hello"
      direct_response:
        status: 405
        body:
          inline_string: "Method Not Allowed"
    
    # General route for other paths
    - match:
        prefix: "/"
      direct_response:
        status: 480